server:
  host: 0.0.0.0
  port: 8000
logging:
  log_level: DEBUG
s3:
  endpoint: http://localhost:9000
  bucket: aggapi-documentation
  force_path_style: true
  load_on_start: true
fs:
  local_dir: www/public
  statics: site