# Stable features
max_width = 120
use_field_init_shorthand = true
newline_style = "Unix"
edition = "2021"
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
#fn_single_line = true
#brace_style = "SameLineWhere"
#combine_control_expr = false
fn_call_width = 90